#ansible-playbook jenkins-x-minishift.yml -v

---
- hosts: localhost
  tasks:
  - name: Clean up - stop & uninstall minishift
    command: "{{ item }}"
    with_items:
    - minishift stop
    - eval $(minishift docker-env -u)
    - minishift delete
    - brew cask uninstall --force minishift
    ignore_errors: yes
  - name: Clean up - rm -rf ~/.minishift
    file:
      state: absent
      path: "~/.minishift"
    ignore_errors: yes
  - name: Install - install minishift
    command: brew cask install minishift
  - name: Install - install addons minishift
    command: minishift addons install --defaults
  - name: Install - enable addons minishift
    command: minishift addons enable admin-user
  - name: jx
    command: jx
    args:
      chdir: ~/Downloads
